[module-base]
format-background = ${colors.background-alt}
format-padding = 0
format-margin = 0

[module/date]
type = internal/date

; Seconds to sleep between updates
; Default: 1.0
interval = 1.0

; See https://en.cppreference.com/w/cpp/io/manip/put_time for details on how to format the date string
; NOTE: if you want to use syntax tags here you need to use %%{...}
date = %Y-%m-%d%

; Optional time format
time = %H:%M

; if `date-alt` or `time-alt` is defined, clicking
; the module will toggle between formats
date-alt = %A, %d %B %Y
time-alt = %A %b %d, %G
format = <label>
format-prefix = "${vars-local.icon-date}"
format-prefix-font = 7
format-prefix-foreground = ${colors.primary}
format-background = ${colors.background-alt}

; Available tokens:
;   %date%
;   %time%
;   Default: %date%
label = %time%
label-padding-right = 1

[module/volume]
type=internal/pulseaudio
use-ui-max=false
interval=1

format-volume=<ramp-volume><label-volume>
ramp-volume-0 = "${vars-local.icon-vol}"
ramp-volume-background= ${colors.background-alt}
ramp-volume-foreground=${colors.primary}
ramp-volume-font = 7
label-volume = %percentage%%
label-volume-padding-right = 1
label-volume-foreground=${colors.foreground}
label-volume-background=${colors.background-alt}

format-muted=<label-muted>
format-muted-prefix = "  "
format-muted-prefix-font = 7
format-muted-prefix-foreground = ${colors.red}
format-muted-background = ${colors.background-alt}
label-muted=MUTE
label-muted-padding-right = 1
label-muted-foreground=${colors.red}

[module/battery]
type = internal/battery
full-at = 99
battery = ${env:BAR_BATTERY:BAT0}
adapter = ${env:BAR_ADAPTER:AC}
poll-interval = 2
time-format = %H:%M

format-charging = <animation-charging><label-charging>
format-charging-prefix = "  "
format-charging-prefix-font = 7
format-charging-prefix-foreground = ${colors.primary}
format-charging-background = ${colors.background-alt}

format-discharging = <ramp-capacity><label-discharging>
format-discharging-background = ${colors.background-alt}

label-charging = %percentage%%
label-charging-padding-right = 1
label-discharging = %percentage%%
label-discharging-padding-right = 1

format-full = <label-full>
format-full-prefix = "${vars-local.icon-bat}"
format-full-prefix-font = 7
format-full-prefix-foreground = ${colors.primary}
format-full-background = ${colors.background-alt}
label-full = %percentage%%
label-full-padding-right = 1

ramp-capacity-0 ="  "
ramp-capacity-1 ="  "
ramp-capacity-2 ="  "
ramp-capacity-3 ="  "
ramp-capacity-4 ="  "
ramp-capacity-foreground = ${colors.primary}
ramp-capacity-font = 7

animation-charging-0 =" "
animation-charging-1 =" "
animation-charging-2 =" "
animation-charging-3 =" "
animation-charging-4 =" "
animation-charging-foreground = ${colors.primary}
animation-charging-font = 7
animation-charging-framerate = 700

[module/backlight]
type = internal/backlight
card = ${env:BACKLIGHT_CARD:intel_backlight}
use-actual-brightness = true
poll-interval = 0
enable-scroll = true
format-prefix = "${vars-local.icon-light}"
format-prefix-font = 7
format-background = ${colors.background-alt}
format-foreground = ${colors.primary}
label = %percentage%%
label-padding-right = 1
scroll-interval = 1

[module/tray]
type = internal/tray
format-background = ${colors.background-alt}
tray-background = ${colors.background-alt}
format-padding = 0
tray-padding = 0
tray-spacing = 8
tray-size = 75%

[module/launcher]
type=custom/text
format = ${vars.launcher-icon-raw}
format-font = 8
format-foreground = ${colors.primary}
format-background = ${colors.background-alt}
format-padding = 1
click-left = bash ~/.config/rofi/bin/launch.sh
click-right = rofi -show run

[module/help-keys]
type = custom/text
format = " Keys "
format-foreground = ${colors.foreground}
format-background = ${colors.background-alt}
click-left = ~/.local/bin/show_cheatsheet.sh
