background            = "{{ colors.surface.default.hex }}"
foreground            = "{{ colors.on_surface.default.hex }}"
cursor                = "{{ colors.primary.default.hex }}"
cursor_text_color     = "{{ colors.surface.default.hex }}"
cursor_reverse        = "{{ colors.surface.default.hex }}"
selection_bg          = "{{ palettes.secondary._30.hex }}"
selection_fg          = "{{ palettes.neutral._95.hex }}"
url_color             = "{{ palettes.tertiary._80.hex }}"
color0                = "{{ palettes.neutral._20.hex }}"
color1                = "{{ palettes.error._70.hex }}"
color2                = "{{ palettes.tertiary._70.hex }}"
color3                = "{{ palettes.secondary._70.hex }}"
color4                = "{{ palettes.primary._70.hex }}"
color5                = "{{ palettes.primary._60.hex }}"
color6                = "{{ palettes.secondary._60.hex }}"
color7                = "{{ palettes.neutral._80.hex }}"
color8                = "{{ palettes.neutral_variant._40.hex }}"
color9                = "{{ palettes.error._80.hex }}"
color10               = "{{ palettes.tertiary._80.hex }}"
color11               = "{{ palettes.secondary._80.hex }}"
color12               = "{{ palettes.primary._80.hex }}"
color13               = "{{ palettes.primary._90.hex }}"
color14               = "{{ palettes.secondary._90.hex }}"
color15               = "{{ palettes.neutral._95.hex }}"
color255              = "{{ palettes.primary._30.hex }}"
color254              = "{{ palettes.primary._70.hex }}"
color253              = "{{ palettes.secondary._30.hex }}"
color252              = "{{ palettes.secondary._70.hex }}"
color251              = "{{ palettes.tertiary._30.hex }}"
color250              = "{{ palettes.tertiary._70.hex }}"
color249              = "{{ palettes.error._30.hex }}"
color248              = "{{ palettes.error._70.hex }}"
color232              = "{{ palettes.primary._90.hex }}"
color233              = "{{ palettes.primary._20.hex }}"
color234              = "{{ palettes.secondary._90.hex }}"
color235              = "{{ palettes.secondary._20.hex }}"
color236              = "{{ palettes.tertiary._90.hex }}"
color237              = "{{ palettes.tertiary._20.hex }}"
color238              = "{{ palettes.error._90.hex }}"
color239              = "{{ palettes.error._20.hex }}"
color240              = "{{ palettes.primary._90.hex }}"
color243              = "{{ palettes.primary._70.hex }}"
color244              = "{{ palettes.error._70.hex }}"
color245              = "{{ palettes.neutral_variant._50.hex }}"
