;==========================================================
; Importing files 
include-file = ~/.config/polybar/colors.ini
include-file = ~/.config/polybar/variables.ini
include-file = ~/.config/polybar/modules.ini

;==========================================================
[bar/main]
width = 100%
height = ${vars.height}
radius = ${vars.radius}
bottom = ${vars.bottom}
dpi = 100
background = ${vars.background}
foreground = ${colors.foreground}
line-size = ${vars.line-size}
border-size = 3pt
border-color = ${vars.background}
module-margin = 0
padding-left= 4pt
padding-right= 4pt
separator =" "
separator-foreground = ${vars.background}

font-0 = ${vars.font-0}
font-1 = ${vars.font-1}
font-2 = ${vars.font-2}
font-3 = ${vars.font-rofi}
font-4 = ${vars.font-symbols}
font-5 = ${vars.font-large}

modules-left = rofi help-keys wifi-btn i3 xwindow tray
modules-right = filesystem cpu backlight temp memory pulseaudio battery time 

cursor-click = pointer
enable-ipc = true
wm-restack = i3
override-redirect = ${vars.override-redirect}

[settings]
screenchange-reload = false
pseudo-transparency = ${vars.pseudo-transparency}
