# Font & Window
font = "JetBrainsMono Nerd Font:size=11:antialias=true:autohint=true"
borderpx = 12
alpha = 1.0
alpha_unfocused = 1.0

# Performance & Buffer
maxlatency = 16
scrollback_lines = 5000

# Keybindings & Theme
include keybindings.conf
include themes/matugen.conf
