;==========================================================
; Importing files - MUST BE AT THE TOP
include-file = ~/.config/polybar/colors.ini
include-file = ~/.config/polybar/variables.ini
include-file = modules.ini

;==========================================================
[bar/main]
width = 100%
height = ${vars.height}
radius = ${vars.radius}
bottom = ${vars.bottom}
dpi = 100
background = ${vars.compact-background}
foreground = ${colors.foreground}
line-size = ${vars.line-size}
border-left-size = ${vars.border-left}
border-right-size = ${vars.border-right}
border-top-size = ${vars.border-top}
border-bottom-size = ${vars.border-bottom}
border-color = #00000000

; Margen 0 para que no interfiera con el margen dinámico de los módulos
module-margin = 0

padding-left= 4pt
padding-right= 4pt
separator =

font-0 = ${vars.font-0}
font-1 = ${vars.font-1}
font-2 = ${vars.font-2}
font-3 = ${vars.font-rofi}
font-4 = ${vars.font-symbols}
font-5 = ${vars.font-large}

; Listas limpias sin espaciadores manuales, agrupados con módulo space
modules-left = ${env:POLY_COMPACT_LEFT}
modules-center = ${env:POLY_COMPACT_CENTER}
modules-right = ${env:POLY_COMPACT_RIGHT}

cursor-click = pointer
enable-ipc = true
wm-restack = i3
override-redirect = ${vars.override-redirect}

[settings]
screenchange-reload = false
pseudo-transparency = ${vars.pseudo-transparency}
