exec --no-startup-id ~/.config/polybar/launch.sh
exec_always --no-startup-id picom --config ~/.config/picom/picom.conf
exec_always --no-startup-id $dots_cmd $current_env wp_select.sh -C "$(cat ~/.config/i3/wall)"
exec --no-startup-id ~/.local/bin/recolor_folders --restore
exec --no-startup-id dunst
exec --no-startup-id xsettingsd -c $HOME/.config/xsettingsd/xsettingsd.conf
exec --no-startup-id $polkit_agent &

