# Utilice Mouse+$mod para arrastrar ventanas flotantes a la posición deseada
floating_modifier $mod

# mover ventanas en mosaico mediante arrastrar y soltar haciendo clic izquierdo en la barra de título, o haciendo clic izquierdo en cualquier lugar de la ventana mientras mantiene presionado el modificador flotante.
#tiling_drag modifier titlebar

for_window [class=".*"] border pixel 1
# for_window [class="kitty"] floating enable, resize set 800 500, move position center
#for_window [class="Pcmanfm"] floating enable 
for_window [title="i3-cheatsheet"] floating enable, border pixel 3, move position center
for_window [instance="wifi-qr"] floating enable, resize set 520 480, move position center
for_window [class="(?i)wifi-qr"] floating enable, resize set 520 480, move position center


