;==========================================================
; Importing files - MUST BE AT THE TOP
include-file = ~/.config/polybar/colors.ini
include-file = ~/.config/polybar/variables.ini
include-file = modules.ini

;==========================================================
[bar/main]
width = 100%
height = ${vars.height}
radius = ${vars.radius}
bottom = ${vars.bottom}
dpi = 100
background = ${vars.background}
foreground = ${colors.foreground}
border-size = 5
border-color = ${vars.background}

; MARGEN NATIVO: Infalible contra espacios dobles
module-margin = 7px

padding-left= 4pt
padding-right= 4pt
separator =

font-0 = ${vars.font-0}
font-1 = ${vars.font-1}
font-2 = ${vars.font-2}
font-3 = ${vars.font-rofi}
font-4 = ${vars.font-symbols}
font-5 = ${vars.font-large}

modules-left = rofi i3 xwindow tray
modules-center = time
modules-right = filesystem cpu backlight temp memory pulseaudio battery

cursor-click = pointer
enable-ipc = true
wm-restack = i3
override-redirect = ${vars.override-redirect}

[settings]
screenchange-reload = false
pseudo-transparency = ${vars.pseudo-transparency}
